parameters:
- name: commands
  type: string
  default: ''

jobs:
- job: check_skip
  pool:
    vmImage: ubuntu-latest
  steps:
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    - checkout: self
      path: s/self
    - checkout: OpenAstronomy
      path: s/azure-pipelines-templates
    - bash: $(Pipeline.Workspace)/s/azure-pipelines-templates/check-skip.sh
      workingDirectory: $(Pipeline.Workspace)/s/self
      name: search
      env:
        COMMIT_MESSAGE: $(Build.SourceVersionMessage)
        ${{ if parameters.commands }}:
          SKIP_COMMANDS: ${{ parameters.commands }}
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - bash: echo "##vso[task.setvariable variable=found;isOutput=true]false"
      name: search
